/**
 * Common countries and US states for searchable selection.
 * Extend as needed for your use case.
 */

export const COUNTRIES = [
  'United States',
  'Canada',
  'United Kingdom',
  'Australia',
  'Germany',
  'France',
  'India',
  'Japan',
  'China',
  'Brazil',
  'Mexico',
  'Spain',
  'Italy',
  'Netherlands',
  'South Korea',
  'Ireland',
  'New Zealand',
  'Singapore',
  'Sweden',
  'Switzerland',
  'Belgium',
  'Austria',
  'Norway',
  'Denmark',
  'Finland',
  'Portugal',
  'Poland',
  'South Africa',
  'Argentina',
  'Chile',
  'Colombia',
  'Israel',
  'United Arab Emirates',
  'Saudi Arabia',
  'Malaysia',
  'Philippines',
  'Thailand',
  'Vietnam',
  'Indonesia',
  'Egypt',
  'Nigeria',
  'Kenya',
  'Ghana',
  'Pakistan',
  'Bangladesh',
  'Turkey',
  'Russia',
  'Ukraine',
  'Greece',
  'Czech Republic',
  'Romania',
  'Hungary',
  'Other',
].map((name) => ({ label: name, value: name }))

export const US_STATES = [
  'Alabama',
  'Alaska',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming',
  'District of Columbia',
].map((name) => ({ label: name, value: name }))
